The purpose of this notebook is to demonstrate how you can get forecast-ready features for your locations at scale. To do this, we will use the [Features API](https://docs.predicthq.com/api/features). 

Make sure you have successfully created Beam Analyses for all your locations before running this notebook. The output is a ready-to-use dataframe of features for each of your locations.

# Steps

* [Setup](#setup)
* [Step 1. Prepare Locations](#step-1-prepare-locations)
* [Step 2. Features API: Get Features](#step-2-features-api-get-features)

# Setup

Complete the following steps before proceeding:

1. Install `requirements.txt`
2. Replace `ACCESS_TOKEN` with a valid token (for help creating an access token, see [the API Quickstart](https://docs.predicthq.com/getting-started/api-quickstart))

In [1]:
# install requirements
# %pip install --user -r requirements.txt

In [ ]:
import pandas as pd
import json
import os
import phq_api_utils as pau

In [ ]:
DATA_DIR = "data"
OUTPUT_DIR = "output"

ACCESS_TOKEN = "REPLACE_WITH_ACCESS_TOKEN"

# Step 1. Prepare Locations

**Location-level Features**

Prepare a config file with the following information:

1. `analysis_id`: Beam Analysis ID

2. `start` and `end`: (optional) the date range to calculate features for, defaults to 2 years before and 3 months after today if not provided

**Group-level Features**

In addition to the above, you will also need to provide the following for each Analysis:

1. `group_id`: the Group ID associated with the Analysis

See the example `config` and `group_config` below for how this looks.

In [ ]:
# load config file
with open(os.path.join(OUTPUT_DIR, "config_updated.json"), "r") as f:
    config = json.load(f)

config = pau.supplement_config(config=config)

In [5]:
config

{'store_0': {'lat': 40.74559205863674,
  'lon': -73.9945205785237,
  'analysis_name': 'store_0_daily_analysis',
  'industry': 'restaurants',
  'start': '2017-01-02',
  'end': '2019-12-31',
  'analysis_id': 'itHSB5-WICk',
  'upload_status': 202,
  'readiness_status': 'ready'},
 'store_1': {'lat': 33.971191942428334,
  'lon': -118.16436160102515,
  'analysis_name': 'store_1_daily_analysis',
  'industry': 'restaurants',
  'start': '2017-01-02',
  'end': '2018-11-30',
  'analysis_id': 'XCwohExDJH4',
  'upload_status': 202,
  'readiness_status': 'ready'},
 'store_2': {'lat': 40.751582853596915,
  'lon': -73.98155897848956,
  'analysis_name': 'store_2_monday_weekly_analysis',
  'industry': 'restaurants',
  'start': '2017-01-09',
  'end': '2019-12-23',
  'analysis_id': 'yFtsOK53__M',
  'upload_status': 202,
  'readiness_status': 'ready'},
 'store_3': {'lat': 40.74559205863674,
  'lon': -73.9945205785237,
  'analysis_name': 'store_3_monday_weekly_analysis',
  'industry': 'restaurants',
  'start': '2017-01-09',
  'end': '2019-12-23',
  'analysis_id': 'rUpVMrAcqCQ',
  'upload_status': 202,
  'readiness_status': 'ready'}}

In [6]:
# load group config file
with open(os.path.join(OUTPUT_DIR, "group_config_updated.json"), "r") as f:
    group_config = json.load(f)

In [7]:
group_config

{'group_A': {'name': 'group_A_analysis',
  'locations': ['store_0', 'store_1'],
  'analysis_ids': ['itHSB5-WICk', 'XCwohExDJH4'],
  'group_id': '4rKOnAWv690',
  'group_status': {'readiness_status': 'ready',
   'feature_importance_processing_completed': True}},
 'group_B': {'name': 'group_B_analysis',
  'locations': ['store_2', 'store_3'],
  'analysis_ids': ['yFtsOK53__M', 'rUpVMrAcqCQ'],
  'group_id': 'ut4LtFr5xFw',
  'group_status': {'readiness_status': 'ready',
   'feature_importance_processing_completed': True}}}

# Step 2. Features API: Get Features

Get relevant features for your locations using [Features API](https://docs.predicthq.com/api/features). Features that are not relevant for a specific location appear as `NaN` and should be ignored.

**Location-level Features**

In [8]:
# get features data
features_data = []
for location, info in config.items():
    print(f"Getting features data for {location}...")

    try:
        features = pau.get_features(location=info, access_token=ACCESS_TOKEN)
        features.insert(0, "location", location)

        features_data.append(features)
        print(f"--- features retrieved")

    except Exception as e:
        print(f"--- an error occurred: {e}")

features_df = pd.concat(features_data)

# save features
features_df.to_csv(os.path.join(OUTPUT_DIR, "features.csv"), index=False)

Getting features data for store_0...
--- features retrieved
Getting features data for store_1...
--- features retrieved
Getting features data for store_2...
--- features retrieved
Getting features data for store_3...
--- features retrieved

In [9]:
features_df

,location,date,phq_attendance_community_hospitality_stats_sum,phq_attendance_conferences_hospitality_stats_sum,phq_attendance_expos_hospitality_stats_sum,phq_attendance_sports_hospitality_stats_sum,phq_impact_academic_exam_stats_sum,phq_impact_academic_holiday_stats_sum,phq_impact_observances_hospitality_stats_sum,phq_impact_public_holidays_hospitality_stats_sum,...,phq_impact_severe_weather_cold_wave_storm_retail_stats_max,phq_attendance_school_holidays_stats_sum,phq_attendance_festivals_hospitality_stats_sum,phq_impact_severe_weather_heat_wave_retail_stats_max,phq_impact_severe_weather_tornado_retail_stats_max,phq_attendance_concerts_hospitality_stats_sum,phq_attendance_performing_arts_hospitality_stats_sum,phq_impact_school_holidays_stats_sum,phq_impact_severe_weather_flood_retail_stats_max,phq_impact_severe_weather_thunderstorm_retail_stats_max
0,store_0,2017-01-02,6704.0,0.0,0.0,26115,0.0,0.0,0,95,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,store_0,2017-01-03,6704.0,0.0,0.0,31876,0.0,0.0,0,13,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,store_0,2017-01-04,6704.0,0.0,0.0,26115,0.0,0.0,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,store_0,2017-01-05,6704.0,0.0,0.0,13760,0.0,0.0,9,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,store_0,2017-01-06,8380.0,0.0,0.0,19500,0.0,0.0,10,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,store_3,2019-11-25,0.0,0.0,30729.0,140921,0.0,2179.0,131,175,...,23,NaN,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0
151,store_3,2019-12-02,35200.0,0.0,120008.0,143121,0.0,0.0,155,0,...,80,NaN,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0
152,store_3,2019-12-09,11300.0,0.0,32706.0,39201,910.0,0.0,140,0,...,0,NaN,31785.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0
153,store_3,2019-12-16,0.0,0.0,7295.0,144325,2132.0,1486.0,30,13,...,0,NaN,7382.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0
154,store_3,2019-12-23,0.0,0.0,0.0,25526,0.0,575.0,100,34,...,0,NaN,870.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0

**Group-level Features**

In [10]:
# get features data
features_data = []
for group, group_info in group_config.items():
    group_id = group_info.get("group_id", None)

    try:
        for location in group_info["locations"]:
            print(f"Getting features data for {location} in {group}...")

            info = config[location]
            try:
                features = pau.get_features(
                    location=info, access_token=ACCESS_TOKEN, group_id=group_id
                )
                features.insert(0, "group", group)
                features.insert(1, "location", location)
                features_data.append(features)

                print(f"--- features retrieved")

            except Exception as e:
                print(f"--- an error occurred: {e}")

    except Exception as e:
        print(f"--- an error occurred: {e}")

features_df = pd.concat(features_data)

# save features
features_df.to_csv(os.path.join(OUTPUT_DIR, "group_features.csv"), index=False)

Getting features data for store_0 in group_A...
--- features retrieved
Getting features data for store_1 in group_A...
--- features retrieved
Getting features data for store_2 in group_B...
--- features retrieved
Getting features data for store_3 in group_B...
--- features retrieved

In [11]:
features_df

,group,location,date,phq_attendance_community_hospitality_stats_sum,phq_attendance_conferences_hospitality_stats_sum,phq_attendance_expos_hospitality_stats_sum,phq_attendance_sports_hospitality_stats_sum,phq_impact_academic_exam_stats_sum,phq_impact_academic_holiday_stats_sum,phq_impact_observances_hospitality_stats_sum,phq_impact_public_holidays_hospitality_stats_sum,phq_impact_severe_weather_cold_wave_retail_stats_max,phq_impact_severe_weather_cold_wave_storm_retail_stats_max,phq_impact_severe_weather_heat_wave_retail_stats_max,phq_impact_severe_weather_tornado_retail_stats_max,phq_attendance_performing_arts_hospitality_stats_sum,phq_impact_severe_weather_flood_retail_stats_max,phq_impact_severe_weather_thunderstorm_retail_stats_max
0,group_A,store_0,2017-01-02,6704.0,0,0,26115,0,0,0,95,0,0,0.0,0.0,NaN,NaN,NaN
1,group_A,store_0,2017-01-03,6704.0,0,0,31876,0,0,0,13,0,0,0.0,0.0,NaN,NaN,NaN
2,group_A,store_0,2017-01-04,6704.0,0,0,26115,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN
3,group_A,store_0,2017-01-05,6704.0,0,0,13760,0,0,9,0,0,0,0.0,0.0,NaN,NaN,NaN
4,group_A,store_0,2017-01-06,8380.0,0,0,19500,0,0,10,0,0,0,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,group_B,store_3,2019-11-25,NaN,0,30729,140921,0,2179,131,175,0,23,NaN,NaN,0.0,0.0,0.0
151,group_B,store_3,2019-12-02,NaN,0,120008,143121,0,0,155,0,0,80,NaN,NaN,0.0,0.0,0.0
152,group_B,store_3,2019-12-09,NaN,0,32706,39201,910,0,140,0,0,0,NaN,NaN,0.0,0.0,0.0
153,group_B,store_3,2019-12-16,NaN,0,7295,144325,2132,1486,30,13,0,0,NaN,NaN,0.0,0.0,0.0
154,group_B,store_3,2019-12-23,NaN,0,0,25526,0,575,100,34,0,0,NaN,NaN,0.0,0.0,0.0